// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3I-TEQuC3q24rhGodowDTZGjn-Zdg8Uo',
    appId: '1:771071301820:web:bb47f45fa1cfb12cb958b9',
    messagingSenderId: '771071301820',
    projectId: 'hadi-lhfaf',
    authDomain: 'hadi-lhfaf.firebaseapp.com',
    storageBucket: 'hadi-lhfaf.firebasestorage.app',
    measurementId: 'G-BM7Z3KJ12P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMiYf_W1jTuU9I_8I5HFxIlsVey9SjSKQ',
    appId: '1:771071301820:android:8626d37e1ba32a77b958b9',
    messagingSenderId: '771071301820',
    projectId: 'hadi-lhfaf',
    storageBucket: 'hadi-lhfaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFFvEolQB0KaRUWw2v25oqQRCmQIzTljw',
    appId: '1:771071301820:ios:850f6c8a4db98319b958b9',
    messagingSenderId: '771071301820',
    projectId: 'hadi-lhfaf',
    storageBucket: 'hadi-lhfaf.firebasestorage.app',
    iosBundleId: 'com.example.hadiLhafaf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFFvEolQB0KaRUWw2v25oqQRCmQIzTljw',
    appId: '1:771071301820:ios:850f6c8a4db98319b958b9',
    messagingSenderId: '771071301820',
    projectId: 'hadi-lhfaf',
    storageBucket: 'hadi-lhfaf.firebasestorage.app',
    iosBundleId: 'com.example.hadiLhafaf',
  );
}
